### ISSUE TITLE
Settlement Reconciliation

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#10]
There is something weird going on.

I run the settlement report for 31/07/2014. In the report you will find PMT00006232 as Pending PAID.

Then I go to the DB and execute "select \* from [dbo].[AGENT_Settlement] where PayoutReferenceID = 'PMT00006232'"

I found out the transaction is in "CCBZJ_DZ_SY_20140801". Then I go to the server and open the file. To my surprise, I cannot find the transaction (PMT00006232) in the file.

Is that mean we have a bug at reading the file into the system?

**Comment by jctopo** [comment]
The transaction is on the Pending Paids grid. That means this transaction have been paid in CEG, but it doesn't come with in any CCB conciliation file, that's why you couldn't find it.

**Comment by pmt-it** [comment]
JC, I don't agree. Transaction ID PMT00006232 is PAID on CCB side but its RFP in CEG side. I think you got missed up with PMT00006230. Please check again.

**Comment by jctopo** [comment]
This could be due to CCB sending a file with the same name, diferent data, the process will replace the file in the archive folder if have the same name. I got the file where that transaction exists.

**Comment by pmt-it** [comment]
OK
