### ISSUE TITLE
National Fees ordering

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#11]
We need to sort the table in the following order:

FromCountryCode order by ASC
FromCurrencyCode order by ASC
ToCountryCode order by ASC
ToCurrencyCode order by ASC
ProductDesc order by ASC
FaceAmountFrom order by ASC

![image](https://cloud.githubusercontent.com/assets/6502098/3932809/0db48bcc-2472-11e4-9f59-1c72b18ea2e9.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Tested and OK
