### ISSUE TITLE
OFAC Listing display

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#12]
JC, we need to display filter to see what records the compliance will be concerning about. I have wrote you a pseudo code for the filter. Currently Admin Panel is creating 53 records. After displaying the filters, we are showing 11.

declare @intProbability smallint
select @intProbability = value from [dbo].[OFAC_Settings] where settingName = 'OFAC_Probability'

select \* from [dbo].[OFAC_Matches] where payoutreferenceID = '10100000098'
and EntryCategory in ('PEP','Sanction List')
and (matchtype = 4 or (matchtype = 5 and Probability >=@intProbability))

![image](https://cloud.githubusercontent.com/assets/6502098/3932910/290748b8-2474-11e4-91ed-dda4c872fd49.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Tested and OK
