### ISSUE TITLE
UNHOLD transaction does not insert entry Notes

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#13]
After clicking the UN-HOLD button, the system does not enter a record to the NOTES table and hence we dont know who un-hold the button

![image](https://cloud.githubusercontent.com/assets/6502098/4051929/8cff8fb0-2d66-11e4-83fd-39f8ca0aec62.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4051944/b1f06678-2d66-11e4-9b67-44def4c7d1bb.png)

**Comment by jctopo** [comment]
UnHold button shouldn't appear on OFAC hits. Fixed

**Comment by pmt-it** [comment]
OK - Fixed.
