### ISSUE TITLE
Reconciliation report for CCB

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#14]
There seem to be a repeating transaction in the Section 2 of the report. See red box. Something wrong in the SQL SELECT?

![image](https://cloud.githubusercontent.com/assets/6502098/4073295/cb34e17c-2e92-11e4-9893-7322eefe545e.png)

**Comment by jctopo** [comment]
Record is duplicated in table

**Comment by pmt-it** [comment]
verified.
