### ISSUE TITLE
OFAC button on Admin Panel

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#18]
If I understand correctly, if I see the transaction is released by 'SYS_OfacCheck', there is no OFAC hit on the transaction. So, I would like to suggest to remove the OFAC button. Because if you click into it, we get an error. This will create a false impression there is something wrong with the OFAC functionality. Also, insert a note in the Notes section stating there is 'No Sanction list found for the transaction'

![image](https://cloud.githubusercontent.com/assets/6502098/4176464/9a54fbbc-3605-11e4-8336-e9702e060b0e.png)

Also, when there is a OFAC hit, change the wording as indicated below

![image](https://cloud.githubusercontent.com/assets/6502098/4176483/dd96465a-3606-11e4-8629-0f0ee6e4c67b.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
