### ISSUE TITLE
Rounding off issue for FX rate

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#19]
See below when creating HKD to EUR. Admin Panel is rounding the FX rate when saving to the system. Also the Admin Panel need to show 4 decimal places

![image](https://cloud.githubusercontent.com/assets/6502098/4176490/5ab0a446-3607-11e4-9dd1-81bcfab4e156.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4176496/7996fe46-3607-11e4-9f4c-4d35523b4262.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
The EDIT screen is rounding off to 2 decimal places. Please check

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
