### ISSUE TITLE
Creating user with same username for POS and Admin Panel

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#20]
When you create a user, say username = james.bond on POS and then you create the same username on Admin Panel. First, you don't get an error message stating the username has been taken. Secondly, the first record (POS) got over-written by the 2nd user (Admin Panel)

Suggestion:
1. Can you have the same username on POS and Admin Panel but you cannot have 2 same users in POS or Admin Panel.

**Comment by jctopo** [comment]
I will pop up an error message when you try to create duplicate user names. We cannot duplicate user names with in all systems.

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
