### ISSUE TITLE
Put FX Rates to four decimal places

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#21]
POS:
1. 
   ![image](https://cloud.githubusercontent.com/assets/6502098/4209775/897d976c-386d-11e4-9c4e-79bc44708036.png)

Admin Panel:
1. http://119.9.85.193/CEG/en-US/Transaction/ViewTran/10100000173?
2. http://119.9.85.193/CEG/en-US/Transaction/Index?from=09%2F09%2F2014&to=10%2F09%2F2014&oriCountry=&desCountry=&oriMasterAgentID=&desMasterAgentID=&productCode=&status=&payoutReferenceID=

**Comment by jctopo** [comment]
Fixed, try again with new tnxs .. !!

**Comment by pmt-it** [comment]
Verified
