### ISSUE TITLE
Agent Commission & Credit Control

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#22]
Currently, for every send transaction, PMT is calculating the SA commission and credit back to the agent's available balance. See screenshot below how the current system works:

![image](https://cloud.githubusercontent.com/assets/6502098/4250292/f628b9b2-3a81-11e4-96f7-6b8f7fc42884.png)

We should create another settlement/calculation type at the MA level. The new option is to not to calculate the SA commission on every send transaction BUT to calculate it on the 1st of each month (manually by the Admin person). The sample calculation should be like the below. All the SA commission get calculated on the 1st of Oct.

![image](https://cloud.githubusercontent.com/assets/6502098/4250481/f34ac38c-3a83-11e4-970b-a9b287282730.png)

Suggestion on how to flag the commission type on MA screen.

![image](https://cloud.githubusercontent.com/assets/6502098/4250660/ef778cb6-3a85-11e4-8873-a86a52e0a02c.png)

**Comment by jctopo** [comment]
Done

**Comment by pmt-it** [comment]
Verified
