### ISSUE TITLE
Upload Sender ID on Create Transaction screen

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#24]

**Comment by jctopo** [comment]
Please elaborate in more detail on the requirement

**Comment by pmt-it** [comment]
Assume, when its a new sender and he/she has no ID document previously uploaded to the system.
When you are trying to send a transaction, and we have setup the transaction requires a Sender ID. At this stage (see below screen shot)

![image](https://cloud.githubusercontent.com/assets/6502098/4291068/224f48f2-3dc1-11e4-8955-c8c4a0671c27.png)

At this stage, you click OK on the message box and then you need to go to CUSTOMER -> SEARCH and then upload the ID document. I think this cause unpleasant customer experience.

It will be great if you we can, after clicking the OK on the message, there is a screen pops up for the user to upload the ID document. Pls see the propose idea in the screen shot below.

![image](https://cloud.githubusercontent.com/assets/6502098/4291155/fef9158a-3dc1-11e4-91ee-ef7d20be2350.png)

**Comment by jctopo** [comment]
We manage to upload Sender ID from Send Transaction screen only for registered customers.

**Comment by pmt-it** [comment]
Verified
