### ISSUE TITLE
Errored transaction not resending to CCB after fix

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#27]
Example: Transaction: 10100000179

We had error when sending transaction to CCB. The error is due to restriction of system hours (8am to 8pm) for account deposit transactions. The issues are:
1. We are not handling this 8am to 8pm issue
2. When we got error from CCB (could be for another reason) we are not able to resend the txns to them.

SP

**Comment by jctopo** [comment]
Added a clear attempt button on View Transaction screen.
Clear attempts on Modify Transaction.

**Comment by pmt-it** [comment]
Can we rename the Label Name: "Clear Attempts" --> "Resend Txn"

**Comment by jctopo** [comment]
I've change the label to Resend Transaction. This button will only appear when the transaction have been rejected by the payer.

**Comment by pmt-it** [comment]
Verified
