### ISSUE TITLE
404 File or Directory not found

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#3]
clicking on jctop has no issue but clicking on steven.poh gives "404 - File or directory not found" error. I think its the "." in the username "steven.poh"

![image](https://cloud.githubusercontent.com/assets/6502098/2881837/be2b41d4-d487-11e3-8a1a-13cc2266e15e.png)

![image](https://cloud.githubusercontent.com/assets/6502098/2881839/c3a558d4-d487-11e3-889f-5edc618a717e.png)

**Comment by jctopo** [comment]
Fixed

![screen](https://cloud.githubusercontent.com/assets/6925815/2912106/e613dac2-d670-11e3-8e03-acea5d3d2c26.jpg)
