### ISSUE TITLE
"Server Error in '/CEG' Application" when get into EDIT Agent

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#31]
Only got this error when click into CCB.

![image](https://cloud.githubusercontent.com/assets/6502098/4352560/78505868-4226-11e4-9d0a-2dcd23dce1c5.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4352561/8286e414-4226-11e4-9708-7d333d9b5578.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
