### ISSUE TITLE
Approach to INTEGRATION_ExportAttempts

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#33]
If I understand correctly, the current process is to insert a record into [INTEGRATION_ExportAttempts] so the export process will pick it up the transaction and export to CCB. In order to export the same record again, you need to delete the previous record from the table.

Although there is nothing wrong with the current process and it is working fine. But in edge cases where we need to see the audit trail when the export has been attempted, we will not be able to see it.

Can we add a new column in the table, e.g. Exported (boolean). When insert the record, Exported = 0; when it has been exported, update Exported = 1.

**Comment by jctopo** [comment]
We have other audit tables like INTEGRATION_IOMEssages.

**Comment by pmt-it** [comment]
ok. I will close this.
