### ISSUE TITLE
IP Address Authorisation

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#34]
When you authorise the IP address (i.e. executing the SP [USP_SECURITY_AuthorizeIPAddress]), you do not verify if the ID belongs to the requestor. 

For example, the requestor with 123.123.123.123, username='abc' has ID = 8 in the [USP_SECURITY_AuthorizeIPAddress] table.

http://119.9.85.193/CEG/en-US/Home/IPActivation/8

And I have another requestor with 192.193.193.193, username='xyz' has ID = 9 in the [USP_SECURITY_AuthorizeIPAddress] table.

http://119.9.85.193/CEG/en-US/Home/IPActivation/9

Then a different user from different IP address (to the above) can go to any of the URL above and try to activate the account and succeed. I think the reason is because in your SP you do not validate the IP address of the PC who is putting down the activation code against the IP address of requesting IP address.

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
