### ISSUE TITLE
Sort Master Agent Name (ASC)

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#36]
![image](https://cloud.githubusercontent.com/assets/6502098/4607239/01d04be0-5247-11e4-8163-20f1b1e686b6.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4607244/3218f6f8-5247-11e4-8b2b-dd89a350a3c6.png)

**Comment by jctopo** [comment]
Completed

**Comment by pmt-it** [comment]
Verified
