### ISSUE TITLE
Audit logs for FX and Fees

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#45]
We need to write a log record when we update or insert a new record for the following tables:
1. (Inser or Update) PRICING_AgentFXRates --writes a log record to -- PRICING_AgentFXRates_log
2. (Inser or Update) PRICING_FXRates --writes a log record to -- PRICING_FXRates 
3. (Inser or Update) PRICING_NationalFeeStructure --writes a log record to -- PRICING_NationalFeeStructure_log 
4. (Inser or Update) PRICING_SendAgentFeeStructure --writes a log record to -- PRICING_SendAgentFeeStructure_log

**Comment by jctopo** [comment]
Completed

**Comment by pmt-it** [comment]
Verified

1.PRICING_AgentFXRates_log
2. PRICING_FXRates_Log
3. PRICING_NationalFeeStructure_log
4. PRICING_SendAgentFeeStructure_log
