### ISSUE TITLE
Agent Credit Incorrect Display 

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#46]
Use KENDY MONEY TRANSFER as an example. Deposit $500 and CEG gived $400 credit limit

![image](https://cloud.githubusercontent.com/assets/6502098/4653920/f50541f0-54b1-11e4-9712-763cee230be2.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4653952/349ebde6-54b2-11e4-814d-bba31e30b090.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4653944/275b1aa8-54b2-11e4-8bc8-6cfac702d9cd.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4653970/6f177058-54b2-11e4-9127-0383e13647e0.png)

When login to POS, the system is displaying $500, not $900.
The system is executing StoredProcedure [dbo].[USP_AGENT_GetAgentBalance]
The SP is adding the Agent's credit limit (in this case 0) and Agent's Balance

Recommendation: We should allow the MA to allocate Agent's credit limit via POS

**Comment by jctopo** [comment]
We get to the conclusion the Credit llimit for this Master Agent and Agent was not properly configured.

**Comment by pmt-it** [comment]
closed
