### ISSUE TITLE
Transaction is on-hold for due to incorrect credit limit calc

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#47]
Use KENDY MONEY TRANSFER as an example. Deposit $500 and CEG gived $400 credit limit

![image](https://cloud.githubusercontent.com/assets/6502098/4653920/f50541f0-54b1-11e4-9712-763cee230be2.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4653952/349ebde6-54b2-11e4-814d-bba31e30b090.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4653944/275b1aa8-54b2-11e4-8bc8-6cfac702d9cd.png)

![image](https://cloud.githubusercontent.com/assets/6502098/4653970/6f177058-54b2-11e4-9127-0383e13647e0.png)

When I create a transaction such that the face amount + fee is between 501 and 899, the transaction will be on hold due to insufficient fund.

**Comment by jctopo** [comment]
You are mixing MA credit limit with its A limit.

**Comment by pmt-it** [comment]
OK - Confusion verified.
