### ISSUE TITLE
Inactivity Message

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#49]
We could borrow this message from Rackspace. The seconds keep counting down :)

![image](https://cloud.githubusercontent.com/assets/6502098/4658731/1d94f1d2-5503-11e4-99cb-b7a7acbecc18.png)

**Comment by jctopo** [comment]
We have seconds counting down as well, whats the problem with our message?

**Comment by pmt-it** [comment]
I didnt see the message when I raised this - now I can see the msg now, No fx is needed at the moment

**Comment by pmt-it** [comment]
Verified
