### ISSUE TITLE
Unable to update API User

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#50]
Trying to udpate email address of an api user but encounter error (username got reset)

![image](https://cloud.githubusercontent.com/assets/6502098/4686446/e8fcb0b0-5645-11e4-8217-b0354d0cb614.png)

Update email address and Click SAVE
![image](https://cloud.githubusercontent.com/assets/6502098/4686473/35933ce6-5646-11e4-8fc1-2e797ffa921a.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
