### ISSUE TITLE
Incorrect date format

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#57]
![image](https://cloud.githubusercontent.com/assets/6502098/5515555/6cc3d6d2-8867-11e4-9c32-1d5e87c33ff4.png)

**Comment by jctopo** [comment]
Fixed.

![57](https://cloud.githubusercontent.com/assets/6925815/5598180/ed493510-9265-11e4-8bf4-7840febdd358.jpg)

**Comment by pmt-it** [comment]
OK
