### ISSUE TITLE
RMB Process - Default date range (FROM and TO)

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#65]
![image](https://cloud.githubusercontent.com/assets/6502098/5807588/b9a3aa5a-a01c-11e4-976e-57a604a0c0db.png)

The reason for this is because the transaction can be on the queue for couple of days or weeks if CEG cannot reach out to Receiver or having difficulty contacting sender.

**Comment by pmt-it** [comment]
![image](https://cloud.githubusercontent.com/assets/6502098/5826892/532d6298-a0ee-11e4-80c5-e34eae68f3bd.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
All of the above has been developed.

New requirement (something I thought of) -- Can you default the Status = CONFIRMED when the screen is load up?

**Comment by pmt-it** [comment]
Also, its very weird. I can search for the transaction "CEG Transaction - Call" area for 10401003280

But I cannot find the transaction for 10401003281 but both transaction are in the same status - awaiting for CEG to call the receiver

**Comment by pmt-it** [comment]
ok
