### ISSUE TITLE
RMB Process - Data not saving correctly in the system after changing one of the 3 elements of verifying receiver's account info for RMB process

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#66]
You need to follow this procedure to reproduce the bug.
1. Just send a RMB Account Deposit transaction. Lets say the receiver name is "Jackie Chan" and the Bank Name = Bank of China and Account Number is 987654321987. Go through the whole process until you marked the transaction as paid.
2. Send another transaction to the same receiver, Bank and Account Number. You will notice this time, you dont need to CALL RECEIVER as it is the same data as in Step 1. 

EVERYTHING IS WORKING AS EXPECTED.
1. Send a new transaction to the same receiver "Jackie Chan", same Account Number "987654321987" but to a different Bank, say, China Construction Bank.

You will notice when you go to "CEG Transaction - Call" section and view the transaciton, you will notice the following data missing as shown the screen shot below:

![image](https://cloud.githubusercontent.com/assets/6502098/5807957/140a3038-a020-11e4-9b90-89d812367b7a.png)

Some example of the transactions who has this bug, you can find the transaction number in the screen below:

![image](https://cloud.githubusercontent.com/assets/6502098/5807994/778b3d5a-a020-11e4-8e7b-02b56d68eaf4.png)

**Comment by jctopo** [comment]
Fixed , Released

**Comment by pmt-it** [comment]
Fixed
