### ISSUE TITLE
RMB Process - Add Notes area

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#67]
1. Allow user to add Notes to the transaction if you click on Reject Transaction button
2. Validate data-input when cilck on SAVE button

![image](https://cloud.githubusercontent.com/assets/6502098/5808141/322a3e30-a022-11e4-9cec-c2cc5cb9bead.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
I cannot see a new label and text box for entering notes.

**Comment by jctopo** [comment]
You need to hit the Reject Transaction button. A popup dialog box will appear

**Comment by pmt-it** [comment]
The Reject Button is showing a new pop up screen --good

The SAVE button still gives error when you have not input any data -- data validation not implemented?

**Comment by pmt-it** [comment]
Both issues fixed
