### ISSUE TITLE
RMB Process - Different screen behaviour (missing Reject Transaction button)

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#68]
I don't understand why in one screen, the REJECT TRANSACTION button is available and the other is missing

![image](https://cloud.githubusercontent.com/assets/6502098/5808181/ad06a652-a022-11e4-934b-9c2f052b0953.png)

![image](https://cloud.githubusercontent.com/assets/6502098/5808184/b10a67fc-a022-11e4-8a64-dd55d4036491.png)

**Comment by jctopo** [comment]
We agreed this was because the transaction status. The transaction status was added as part of the information.

**Comment by pmt-it** [comment]
OK
