### ISSUE TITLE
Reason for Remittance

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#8]
This link takes you to SETTINGS screen.

![image](https://cloud.githubusercontent.com/assets/6502098/3867710/8c3015b8-200b-11e4-9496-5c6ad20e5b8e.png)

![image](https://cloud.githubusercontent.com/assets/6502098/3867712/940b69ae-200b-11e4-826f-dd69375ec878.png)

**Comment by jctopo** [comment]
Fixed
